-- Rerunnable bootstrap schema for Pivot Horses.
-- Safe reruns rely on:
-- - create table if not exists
-- - alter table ... add column if not exists
-- - drop policy if exists + create policy
-- - create or replace function
-- - drop trigger if exists + create trigger
--
-- Modular versions of this schema also live in:
-- - supabase/schema_parts/00_base.sql
-- - supabase/schema_parts/10_community.sql
-- - supabase/schema_parts/20_breeding.sql

create extension if not exists pgcrypto;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  profile_display_name text;
  base_handle text;
  profile_handle text;
  profile_email text;
begin
  profile_email := coalesce(new.email, new.id::text || '@pivot.local');
  profile_display_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
    split_part(profile_email, '@', 1),
    'Player'
  );
  base_handle := '@' || lower(
    regexp_replace(profile_display_name, '[^a-zA-Z0-9]+', '', 'g')
  );
  if base_handle = '@' then
    base_handle := '@player';
  end if;
  profile_handle := base_handle;

  if exists (select 1 from public.profiles where handle = profile_handle) then
    profile_handle := base_handle || substr(replace(new.id::text, '-', ''), 1, 8);
  end if;

  insert into public.profiles (
    id,
    email,
    display_name,
    handle,
    stable_name,
    favorite_breed,
    accent_value,
    coin_balance
  )
  values (
    new.id,
    profile_email,
    profile_display_name,
    profile_handle,
    profile_display_name || ' Stable',
    'Arabian',
    15003876,
    7000
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  display_name text not null,
  handle text unique not null,
  stable_name text not null,
  bio text not null default '',
  favorite_breed text not null default 'Arabian',
  accent_value integer not null default 15003876,
  coin_balance integer not null default 7000,
  inventory jsonb not null default '{}'::jsonb,
  stable_expansion_tier integer not null default 0,
  stable_expansion_renews_at text,
  prenatal_boosted_pregnancy_ids jsonb not null default '[]'::jsonb,
  carrot_boosted_horse_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.horses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  registry_id text unique not null,
  registered_name text not null,
  current_name text not null,
  breed text not null,
  sex text not null,
  generation integer not null default 1,
  age_days integer not null default 1,
  breeding_retirement_days integer not null default 35,
  starter_tier text not null,
  price integer not null default 0,
  transfer_count integer not null default 0,
  is_mutant boolean not null default false,
  is_public_listing boolean not null default false,
  is_featured_profile_horse boolean not null default false,
  is_listed_for_sale boolean not null default false,
  genetic_profile jsonb not null default '{}'::jsonb,
  care_stats jsonb not null default '{}'::jsonb,
  lineage_memory jsonb not null default '{}'::jsonb,
  special_traits jsonb not null default '[]'::jsonb,
  dam_snapshot jsonb,
  sire_snapshot jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.horse_traits (
  id bigint generated by default as identity primary key,
  horse_id uuid not null references public.horses(id) on delete cascade,
  trait_type text not null,
  trait_option text not null,
  rarity text not null,
  sort_order integer not null default 0
);

create table if not exists public.horse_listings (
  id uuid primary key default gen_random_uuid(),
  horse_id uuid unique not null references public.horses(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  buyer_price integer not null,
  seller_payout integer not null,
  status text not null default 'open',
  created_at timestamptz not null default timezone('utc', now()),
  sold_at timestamptz
);

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (follower_id, followee_id),
  constraint follows_not_self check (follower_id <> followee_id)
);

create table if not exists public.horse_likes (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  horse_id uuid not null references public.horses(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (profile_id, horse_id)
);

create table if not exists public.pregnancies (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  dam_id uuid not null references public.horses(id) on delete cascade,
  dam_name text not null default 'Dam',
  sire_id uuid not null references public.horses(id) on delete cascade,
  sire_name text not null default 'Sire',
  unborn_foal_name text not null,
  registry_id text not null default 'PENDING',
  breed text not null default 'Horse',
  foal_payload jsonb not null,
  conceived_at timestamptz not null default timezone('utc', now()),
  due_at timestamptz not null,
  dam_cooldown_ends_at timestamptz not null default timezone('utc', now()),
  sire_cooldown_ends_at timestamptz not null default timezone('utc', now()),
  is_mutant boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  delivered_at timestamptz
);

alter table public.pregnancies
  add column if not exists dam_name text not null default 'Dam',
  add column if not exists sire_name text not null default 'Sire',
  add column if not exists registry_id text not null default 'PENDING',
  add column if not exists breed text not null default 'Horse',
  add column if not exists conceived_at timestamptz not null default timezone('utc', now()),
  add column if not exists dam_cooldown_ends_at timestamptz not null default timezone('utc', now()),
  add column if not exists sire_cooldown_ends_at timestamptz not null default timezone('utc', now()),
  add column if not exists is_mutant boolean not null default false;

create sequence if not exists public.horse_registry_number_seq
start with 101
increment by 1;

create or replace function public.reserve_horse_registry_id()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  loop
    candidate := 'PH' || nextval('public.horse_registry_number_seq')::text;
    exit when not exists (
      select 1
      from public.horses
      where registry_id = candidate
    )
    and not exists (
      select 1
      from public.pregnancies
      where registry_id = candidate
        and delivered_at is null
    );
  end loop;

  return candidate;
end;
$$;

create table if not exists public.breeding_cooldowns (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  horse_id uuid not null references public.horses(id) on delete cascade,
  horse_name text not null,
  sex text not null,
  reason text not null,
  ends_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mating_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  dam_id uuid not null references public.horses(id) on delete cascade,
  dam_name text not null,
  sire_id uuid not null references public.horses(id) on delete cascade,
  sire_name text not null,
  started_at timestamptz not null default timezone('utc', now()),
  ends_at timestamptz not null,
  standard_pregnancy_payload jsonb not null,
  mutant_pregnancy_payload jsonb not null,
  resolved_outcome text,
  resolved_at timestamptz
);

create table if not exists public.breeding_outcomes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  mating_session_id uuid not null unique references public.mating_sessions(id) on delete cascade,
  dam_id uuid not null references public.horses(id) on delete cascade,
  sire_id uuid not null references public.horses(id) on delete cascade,
  outcome_type text not null,
  pregnancy_id uuid references public.pregnancies(id) on delete set null,
  foal_registry_id text,
  is_mutant boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists mating_sessions_one_active_per_owner
on public.mating_sessions (owner_id)
where resolved_at is null;

alter table public.profiles enable row level security;
alter table public.horses enable row level security;
alter table public.horse_traits enable row level security;
alter table public.horse_listings enable row level security;
alter table public.follows enable row level security;
alter table public.horse_likes enable row level security;
alter table public.pregnancies enable row level security;
alter table public.breeding_cooldowns enable row level security;
alter table public.mating_sessions enable row level security;
alter table public.breeding_outcomes enable row level security;

drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read"
on public.profiles
for select
using (true);

drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update"
on public.profiles
for update
using (auth.uid() = id);

drop policy if exists "profiles owner insert" on public.profiles;
create policy "profiles owner insert"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "horses public read" on public.horses;
create policy "horses public read"
on public.horses
for select
using (
  is_public_listing = true
  or is_featured_profile_horse = true
  or is_listed_for_sale = true
  or auth.uid() = owner_id
);

drop policy if exists "horses owner write" on public.horses;
create policy "horses owner write"
on public.horses
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "horse traits readable with horse visibility" on public.horse_traits;
create policy "horse traits readable with horse visibility"
on public.horse_traits
for select
using (
  exists (
    select 1
    from public.horses
    where horses.id = horse_traits.horse_id
      and (
        horses.is_public_listing = true
        or horses.is_featured_profile_horse = true
        or horses.is_listed_for_sale = true
        or horses.owner_id = auth.uid()
      )
  )
);

drop policy if exists "horse traits owner write" on public.horse_traits;
create policy "horse traits owner write"
on public.horse_traits
for all
using (
  exists (
    select 1
    from public.horses
    where horses.id = horse_traits.horse_id
      and horses.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.horses
    where horses.id = horse_traits.horse_id
      and horses.owner_id = auth.uid()
  )
);

drop policy if exists "listings public read" on public.horse_listings;
create policy "listings public read"
on public.horse_listings
for select
using (status = 'open' or auth.uid() = seller_id);

drop policy if exists "listings seller write" on public.horse_listings;
create policy "listings seller write"
on public.horse_listings
for all
using (auth.uid() = seller_id)
with check (auth.uid() = seller_id);

drop policy if exists "follows public read" on public.follows;
create policy "follows public read"
on public.follows
for select
using (true);

drop policy if exists "follows owner write" on public.follows;
create policy "follows owner write"
on public.follows
for all
using (auth.uid() = follower_id)
with check (auth.uid() = follower_id);

drop policy if exists "likes public read" on public.horse_likes;
create policy "likes public read"
on public.horse_likes
for select
using (true);

drop policy if exists "likes owner write" on public.horse_likes;
create policy "likes owner write"
on public.horse_likes
for all
using (auth.uid() = profile_id)
with check (auth.uid() = profile_id);

drop policy if exists "pregnancies owner only" on public.pregnancies;
create policy "pregnancies owner only"
on public.pregnancies
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "cooldowns owner only" on public.breeding_cooldowns;
create policy "cooldowns owner only"
on public.breeding_cooldowns
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "mating sessions owner only" on public.mating_sessions;
create policy "mating sessions owner only"
on public.mating_sessions
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "breeding outcomes owner only" on public.breeding_outcomes;
create policy "breeding outcomes owner only"
on public.breeding_outcomes
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

create or replace function public.start_mating_session(
  dam_registry_id text,
  sire_registry_id text,
  standard_pregnancy_payload jsonb,
  mutant_pregnancy_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  dam_row public.horses%rowtype;
  sire_row public.horses%rowtype;
  session_row public.mating_sessions%rowtype;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into dam_row
  from public.horses
  where owner_id = actor_id
    and registry_id = dam_registry_id
  limit 1;

  if not found then
    raise exception 'Dam not found in your stable';
  end if;

  select *
  into sire_row
  from public.horses
  where owner_id = actor_id
    and registry_id = sire_registry_id
  limit 1;

  if not found then
    raise exception 'Sire not found in your stable';
  end if;

  if dam_row.sex <> 'Mare' then
    raise exception 'Dam must be a mare';
  end if;

  if sire_row.sex <> 'Stallion' then
    raise exception 'Sire must be a stallion';
  end if;

  if exists (
    select 1
    from public.mating_sessions
    where owner_id = actor_id
      and resolved_at is null
  ) then
    raise exception 'There is already an active mating session';
  end if;

  if exists (
    select 1
    from public.pregnancies
    where owner_id = actor_id
      and dam_id = dam_row.id
      and delivered_at is null
  ) then
    raise exception 'Dam is already pregnant';
  end if;

  if exists (
    select 1
    from public.breeding_cooldowns
    where owner_id = actor_id
      and horse_id in (dam_row.id, sire_row.id)
      and ends_at > timezone('utc', now())
  ) then
    raise exception 'One of the selected horses is still on cooldown';
  end if;

  insert into public.mating_sessions (
    owner_id,
    dam_id,
    dam_name,
    sire_id,
    sire_name,
    started_at,
    ends_at,
    standard_pregnancy_payload,
    mutant_pregnancy_payload
  )
  values (
    actor_id,
    dam_row.id,
    dam_row.current_name,
    sire_row.id,
    sire_row.current_name,
    timezone('utc', now()),
    timezone('utc', now()) + interval '5 seconds',
    standard_pregnancy_payload,
    mutant_pregnancy_payload
  )
  returning *
  into session_row;

  return jsonb_build_object(
    'id', session_row.id,
    'dam_id', session_row.dam_id,
    'dam_name', session_row.dam_name,
    'sire_id', session_row.sire_id,
    'sire_name', session_row.sire_name,
    'started_at', session_row.started_at,
    'ends_at', session_row.ends_at
  );
end;
$$;

create or replace function public.resolve_mating_session(target_session_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  session_row public.mating_sessions%rowtype;
  pregnancy_row public.pregnancies%rowtype;
  outcome_record public.breeding_outcomes%rowtype;
  outcome_roll integer;
  outcome_type text;
  selected_payload jsonb;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into session_row
  from public.mating_sessions
  where id = target_session_id
    and owner_id = actor_id
  for update;

  if not found then
    raise exception 'Mating session not found';
  end if;

  if session_row.resolved_at is not null then
    return jsonb_build_object(
      'outcome_type', session_row.resolved_outcome,
      'pregnancy_id', (
        select pregnancy_id
        from public.breeding_outcomes
        where mating_session_id = session_row.id
        limit 1
      )
    );
  end if;

  if session_row.ends_at > timezone('utc', now()) then
    raise exception 'Mating session is still in progress';
  end if;

  outcome_roll := floor(random() * 100);
  if outcome_roll < 80 then
    outcome_type := 'pregnant';
    selected_payload := session_row.standard_pregnancy_payload;
  elsif outcome_roll < 90 then
    outcome_type := 'mutant';
    selected_payload := session_row.mutant_pregnancy_payload;
  else
    outcome_type := 'failed';
    selected_payload := null;
  end if;

  delete from public.breeding_cooldowns
  where owner_id = actor_id
    and horse_id = session_row.sire_id;

  insert into public.breeding_cooldowns (
    owner_id,
    horse_id,
    horse_name,
    sex,
    reason,
    ends_at
  )
  values (
    actor_id,
    session_row.sire_id,
    session_row.sire_name,
    'Stallion',
    'Sire recovery',
    timezone('utc', now()) + interval '12 hours'
  );

  if selected_payload is not null then
    insert into public.pregnancies (
      owner_id,
      dam_id,
      dam_name,
      sire_id,
      sire_name,
      unborn_foal_name,
      registry_id,
      breed,
      foal_payload,
      conceived_at,
      due_at,
      dam_cooldown_ends_at,
      sire_cooldown_ends_at,
      is_mutant
    )
    values (
      actor_id,
      session_row.dam_id,
      session_row.dam_name,
      session_row.sire_id,
      session_row.sire_name,
      coalesce(selected_payload ->> 'unbornFoalName', 'Reserved Foal'),
      coalesce(selected_payload ->> 'registryId', 'PENDING'),
      coalesce(selected_payload ->> 'breed', 'Horse'),
      coalesce(selected_payload -> 'foal', '{}'::jsonb),
      timezone('utc', now()),
      timezone('utc', now()) + interval '4 days',
      timezone('utc', now()) + interval '7 days',
      timezone('utc', now()) + interval '12 hours',
      coalesce((selected_payload ->> 'isMutant')::boolean, false)
    )
    returning *
    into pregnancy_row;
  end if;

  update public.mating_sessions
  set resolved_outcome = outcome_type,
      resolved_at = timezone('utc', now())
  where id = session_row.id;

  insert into public.breeding_outcomes (
    owner_id,
    mating_session_id,
    dam_id,
    sire_id,
    outcome_type,
    pregnancy_id,
    foal_registry_id,
    is_mutant
  )
  values (
    actor_id,
    session_row.id,
    session_row.dam_id,
    session_row.sire_id,
    outcome_type,
    pregnancy_row.id,
    pregnancy_row.registry_id,
    outcome_type = 'mutant'
  )
  returning *
  into outcome_record;

  return jsonb_build_object(
    'outcome_type', outcome_type,
    'pregnancy_id', pregnancy_row.id,
    'breeding_outcome_id', outcome_record.id
  );
end;
$$;

create or replace function public.deliver_pregnancy(target_pregnancy_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  pregnancy_row public.pregnancies%rowtype;
  foal_payload jsonb;
  foal_row public.horses%rowtype;
  recovery_ends_at timestamptz;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into pregnancy_row
  from public.pregnancies
  where id = target_pregnancy_id
    and owner_id = actor_id
  for update;

  if not found then
    raise exception 'Pregnancy not found';
  end if;

  if pregnancy_row.delivered_at is not null then
    return jsonb_build_object(
      'horse_id', (
        select id
        from public.horses
        where owner_id = actor_id
          and registry_id = pregnancy_row.registry_id
        limit 1
      ),
      'registry_id', pregnancy_row.registry_id
    );
  end if;

  if pregnancy_row.due_at > timezone('utc', now()) then
    raise exception 'Pregnancy is not ready for delivery';
  end if;

  foal_payload := coalesce(pregnancy_row.foal_payload, '{}'::jsonb);

  insert into public.horses (
    owner_id,
    registry_id,
    registered_name,
    current_name,
    breed,
    sex,
    generation,
    age_days,
    breeding_retirement_days,
    starter_tier,
    price,
    transfer_count,
    is_mutant,
    is_public_listing,
    is_featured_profile_horse,
    is_listed_for_sale,
    genetic_profile,
    care_stats,
    lineage_memory,
    special_traits,
    dam_snapshot,
    sire_snapshot
  )
  values (
    actor_id,
    coalesce(foal_payload ->> 'registry_id', pregnancy_row.registry_id),
    coalesce(foal_payload ->> 'registered_name', pregnancy_row.unborn_foal_name),
    coalesce(foal_payload ->> 'current_name', pregnancy_row.unborn_foal_name),
    coalesce(foal_payload ->> 'breed', pregnancy_row.breed),
    coalesce(foal_payload ->> 'sex', 'Mare'),
    coalesce((foal_payload ->> 'generation')::integer, 1),
    greatest(coalesce((foal_payload ->> 'age_days')::integer, 1), 1),
    coalesce((foal_payload ->> 'breeding_retirement_days')::integer, 35),
    coalesce(foal_payload ->> 'starter_tier', 'basic'),
    coalesce((foal_payload ->> 'price')::integer, 0),
    coalesce((foal_payload ->> 'transfer_count')::integer, 0),
    coalesce((foal_payload ->> 'is_mutant')::boolean, false),
    false,
    false,
    false,
    coalesce(foal_payload -> 'genetic_profile', '{}'::jsonb),
    coalesce(foal_payload -> 'care_stats', '{}'::jsonb),
    coalesce(foal_payload -> 'lineage_memory', '{}'::jsonb),
    coalesce(foal_payload -> 'special_traits', '[]'::jsonb),
    foal_payload -> 'dam_snapshot',
    foal_payload -> 'sire_snapshot'
  )
  on conflict (registry_id) do update
  set owner_id = excluded.owner_id,
      current_name = excluded.current_name,
      age_days = excluded.age_days,
      updated_at = timezone('utc', now())
  returning *
  into foal_row;

  delete from public.horse_traits
  where horse_id = foal_row.id;

  insert into public.horse_traits (
    horse_id,
    trait_type,
    trait_option,
    rarity,
    sort_order
  )
  select
    foal_row.id,
    coalesce(trait_item ->> 'type', 'body_type'),
    coalesce(trait_item ->> 'option', 'Unknown'),
    coalesce(trait_item ->> 'rarity', 'common'),
    trait_index - 1
  from jsonb_array_elements(coalesce(foal_payload -> 'traits', '[]'::jsonb))
    with ordinality as traits(trait_item, trait_index);

  update public.pregnancies
  set delivered_at = timezone('utc', now())
  where id = pregnancy_row.id;

  delete from public.breeding_cooldowns
  where owner_id = actor_id
    and horse_id = pregnancy_row.dam_id;

  recovery_ends_at := pregnancy_row.due_at + interval '3 days';
  if recovery_ends_at > timezone('utc', now()) then
    insert into public.breeding_cooldowns (
      owner_id,
      horse_id,
      horse_name,
      sex,
      reason,
      ends_at
    )
    values (
      actor_id,
      pregnancy_row.dam_id,
      pregnancy_row.dam_name,
      'Mare',
      'Healing',
      recovery_ends_at
    );
  end if;

  return jsonb_build_object(
    'horse_id', foal_row.id,
    'registry_id', foal_row.registry_id,
    'recovery_ends_at', recovery_ends_at
  );
end;
$$;

create or replace function public.purchase_horse_listing(target_listing_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  buyer_id uuid := auth.uid();
  listing_row public.horse_listings%rowtype;
  horse_row public.horses%rowtype;
  buyer_balance integer;
begin
  if buyer_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into listing_row
  from public.horse_listings
  where id = target_listing_id
    and status = 'open'
  for update;

  if not found then
    raise exception 'Listing not found or no longer open';
  end if;

  if listing_row.seller_id = buyer_id then
    raise exception 'You cannot buy your own listing';
  end if;

  select *
  into horse_row
  from public.horses
  where id = listing_row.horse_id
  for update;

  select coin_balance
  into buyer_balance
  from public.profiles
  where id = buyer_id
  for update;

  if buyer_balance is null then
    raise exception 'Buyer profile not found';
  end if;

  if buyer_balance < listing_row.buyer_price then
    raise exception 'Insufficient coin balance';
  end if;

  update public.profiles
  set coin_balance = coin_balance - listing_row.buyer_price,
      updated_at = timezone('utc', now())
  where id = buyer_id;

  update public.profiles
  set coin_balance = coin_balance + listing_row.seller_payout,
      updated_at = timezone('utc', now())
  where id = listing_row.seller_id;

  update public.horses
  set owner_id = buyer_id,
      transfer_count = horse_row.transfer_count + 1,
      is_public_listing = false,
      is_featured_profile_horse = false,
      is_listed_for_sale = false,
      updated_at = timezone('utc', now())
  where id = horse_row.id;

  update public.horse_listings
  set status = 'sold',
      sold_at = timezone('utc', now())
  where id = listing_row.id;

  return jsonb_build_object(
    'horse_id', horse_row.id,
    'registry_id', horse_row.registry_id,
    'buyer_coin_balance', buyer_balance - listing_row.buyer_price,
    'seller_payout', listing_row.seller_payout
  );
end;
$$;

grant execute on function public.purchase_horse_listing(uuid) to authenticated;
grant execute on function public.start_mating_session(text, text, jsonb, jsonb) to authenticated;
grant execute on function public.resolve_mating_session(uuid) to authenticated;
grant execute on function public.deliver_pregnancy(uuid) to authenticated;
grant execute on function public.reserve_horse_registry_id() to authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create table if not exists public.client_event_log (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  status text not null default 'info',
  message text not null,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.error_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  source text not null,
  message text not null,
  stack_trace text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.support_snapshots (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  support_code text not null unique,
  snapshot_summary text not null default '',
  snapshot_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.feedback_submissions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  email text not null default '',
  display_name text not null default '',
  category text not null default 'Suggestion',
  message text not null,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inbox_items (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'message'
    check (kind in ('message', 'notification')),
  title text not null,
  body text not null default '',
  category text not null default 'General',
  action_label text,
  action_payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists client_event_log_owner_created_idx
on public.client_event_log (owner_id, created_at desc);

create index if not exists error_events_owner_created_idx
on public.error_events (owner_id, created_at desc);

create index if not exists support_snapshots_owner_created_idx
on public.support_snapshots (owner_id, created_at desc);

create index if not exists feedback_submissions_owner_created_idx
on public.feedback_submissions (owner_id, created_at desc);

create index if not exists feedback_submissions_category_created_idx
on public.feedback_submissions (category, created_at desc);

create index if not exists inbox_items_owner_kind_created_idx
on public.inbox_items (owner_id, kind, created_at desc);

create index if not exists inbox_items_owner_unread_idx
on public.inbox_items (owner_id, kind)
where read_at is null;

alter table public.client_event_log enable row level security;
alter table public.error_events enable row level security;
alter table public.support_snapshots enable row level security;
alter table public.feedback_submissions enable row level security;
alter table public.inbox_items enable row level security;

drop policy if exists "client event log owner only" on public.client_event_log;
create policy "client event log owner only"
on public.client_event_log
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "error events owner only" on public.error_events;
create policy "error events owner only"
on public.error_events
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "support snapshots owner only" on public.support_snapshots;
create policy "support snapshots owner only"
on public.support_snapshots
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "feedback submissions owner only" on public.feedback_submissions;
create policy "feedback submissions owner only"
on public.feedback_submissions
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "inbox items owner read" on public.inbox_items;
create policy "inbox items owner read"
on public.inbox_items
for select
using (auth.uid() = owner_id);

drop policy if exists "inbox items owner update" on public.inbox_items;
create policy "inbox items owner update"
on public.inbox_items
for update
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

create or replace function public.send_broadcast_inbox_item(
  item_kind text,
  item_title text,
  item_body text,
  item_category text default 'Announcement',
  item_action_label text default null,
  item_action_payload jsonb default '{}'::jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  inserted_count integer := 0;
begin
  if actor_id is null then
    if current_user not in ('postgres', 'supabase_admin') then
      raise exception 'Authentication required';
    end if;
  elsif not exists (
    select 1
    from public.app_admins
    where user_id = actor_id
  ) then
    raise exception 'Admin access required';
  end if;

  if item_kind not in ('message', 'notification') then
    raise exception 'item_kind must be message or notification';
  end if;

  if nullif(trim(item_title), '') is null then
    raise exception 'item_title is required';
  end if;

  insert into public.inbox_items (
    owner_id,
    kind,
    title,
    body,
    category,
    action_label,
    action_payload
  )
  select
    id,
    item_kind,
    trim(item_title),
    coalesce(item_body, ''),
    coalesce(nullif(trim(item_category), ''), 'Announcement'),
    nullif(trim(item_action_label), ''),
    coalesce(item_action_payload, '{}'::jsonb)
  from public.profiles;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

grant execute on function public.send_broadcast_inbox_item(
  text,
  text,
  text,
  text,
  text,
  jsonb
) to authenticated;

create table if not exists public.purchase_receipts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  platform text not null default 'ios',
  product_id text not null,
  transaction_id text not null,
  status text not null default 'pending'
    check (status in ('pending', 'verified', 'rejected')),
  purchased_amount integer not null default 0,
  price_cents integer not null default 0,
  currency text not null default 'USD',
  raw_receipt_hash text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  verified_at timestamptz,
  unique (platform, transaction_id)
);

create table if not exists public.app_admins (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  note text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.support_recovery_audits (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  admin_user_id uuid not null references public.profiles(id) on delete restrict,
  support_code text,
  action text not null default 'profile_state_recovery',
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  note text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists purchase_receipts_owner_created_idx
on public.purchase_receipts (owner_id, created_at desc);

create index if not exists purchase_receipts_status_created_idx
on public.purchase_receipts (status, created_at desc);

create index if not exists support_recovery_audits_owner_created_idx
on public.support_recovery_audits (owner_id, created_at desc);

create index if not exists support_recovery_audits_admin_created_idx
on public.support_recovery_audits (admin_user_id, created_at desc);

alter table public.purchase_receipts enable row level security;
alter table public.app_admins enable row level security;
alter table public.support_recovery_audits enable row level security;

drop policy if exists "purchase receipts owner insert" on public.purchase_receipts;
create policy "purchase receipts owner insert"
on public.purchase_receipts
for insert
with check (auth.uid() = owner_id);

drop policy if exists "purchase receipts owner read" on public.purchase_receipts;
create policy "purchase receipts owner read"
on public.purchase_receipts
for select
using (auth.uid() = owner_id);

drop policy if exists "app admins can read self" on public.app_admins;
create policy "app admins can read self"
on public.app_admins
for select
using (auth.uid() = user_id);

drop policy if exists "support recovery audits admin read" on public.support_recovery_audits;
create policy "support recovery audits admin read"
on public.support_recovery_audits
for select
using (
  auth.uid() = admin_user_id
  or exists (
    select 1
    from public.app_admins
    where user_id = auth.uid()
  )
);

create or replace function public.support_recover_profile_state(
  target_owner_id uuid,
  support_code text default null,
  coin_balance_delta integer default 0,
  replacement_inventory jsonb default null,
  stable_expansion_tier_value integer default null,
  stable_expansion_renews_at_value text default null,
  note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  before_profile jsonb;
  after_profile jsonb;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  if not exists (
    select 1
    from public.app_admins
    where user_id = actor_id
  ) then
    raise exception 'Admin access required';
  end if;

  select jsonb_build_object(
    'coin_balance', coin_balance,
    'inventory', inventory,
    'stable_expansion_tier', stable_expansion_tier,
    'stable_expansion_renews_at', stable_expansion_renews_at,
    'prenatal_boosted_pregnancy_ids', prenatal_boosted_pregnancy_ids,
    'carrot_boosted_horse_ids', carrot_boosted_horse_ids
  )
  into before_profile
  from public.profiles
  where id = target_owner_id
  for update;

  if before_profile is null then
    raise exception 'Profile not found';
  end if;

  update public.profiles
  set
    coin_balance = greatest(0, coin_balance + coin_balance_delta),
    inventory = coalesce(replacement_inventory, inventory),
    stable_expansion_tier = coalesce(
      stable_expansion_tier_value,
      stable_expansion_tier
    ),
    stable_expansion_renews_at = coalesce(
      stable_expansion_renews_at_value,
      stable_expansion_renews_at
    ),
    updated_at = timezone('utc', now())
  where id = target_owner_id
  returning jsonb_build_object(
    'coin_balance', coin_balance,
    'inventory', inventory,
    'stable_expansion_tier', stable_expansion_tier,
    'stable_expansion_renews_at', stable_expansion_renews_at,
    'prenatal_boosted_pregnancy_ids', prenatal_boosted_pregnancy_ids,
    'carrot_boosted_horse_ids', carrot_boosted_horse_ids
  )
  into after_profile;

  insert into public.support_recovery_audits (
    owner_id,
    admin_user_id,
    support_code,
    before_state,
    after_state,
    note
  )
  values (
    target_owner_id,
    actor_id,
    support_code,
    before_profile,
    after_profile,
    coalesce(note, '')
  );

  return jsonb_build_object(
    'owner_id', target_owner_id,
    'before_state', before_profile,
    'after_state', after_profile
  );
end;
$$;

grant execute on function public.support_recover_profile_state(
  uuid,
  text,
  integer,
  jsonb,
  integer,
  text,
  text
) to authenticated;

create table if not exists public.coin_packs (
  product_id text primary key,
  display_name text not null,
  coin_amount integer not null check (coin_amount > 0),
  price_cents integer not null check (price_cents > 0),
  currency text not null default 'USD',
  badge text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.coin_packs enable row level security;

drop policy if exists "coin packs public read" on public.coin_packs;
create policy "coin packs public read"
on public.coin_packs
for select
using (is_active);

insert into public.coin_packs (
  product_id,
  display_name,
  coin_amount,
  price_cents,
  currency,
  badge,
  sort_order,
  is_active
)
values
  ('coins_1100', 'Stable Snack', 1100, 499, 'USD', null, 10, true),
  ('coins_2500', 'Breeder Bundle', 2500, 999, 'USD', null, 20, true),
  ('coins_5000', 'Barn Vault', 5000, 1999, 'USD', 'Most popular', 30, true),
  ('coins_12000', 'Champion Chest', 12000, 4999, 'USD', 'Best value', 40, true)
on conflict (product_id) do update
set
  display_name = excluded.display_name,
  coin_amount = excluded.coin_amount,
  price_cents = excluded.price_cents,
  currency = excluded.currency,
  badge = excluded.badge,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

create or replace function public.grant_verified_coin_purchase(
  target_owner_id uuid,
  target_product_id text,
  target_transaction_id text,
  target_platform text default 'ios',
  target_raw_receipt_hash text default null,
  verification_context jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  pack_row public.coin_packs%rowtype;
  receipt_row public.purchase_receipts%rowtype;
  next_balance integer;
begin
  select *
  into pack_row
  from public.coin_packs
  where product_id = target_product_id
    and is_active;

  if not found then
    raise exception 'Unknown or inactive coin pack';
  end if;

  select *
  into receipt_row
  from public.purchase_receipts
  where platform = target_platform
    and transaction_id = target_transaction_id
  for update;

  if found then
    if receipt_row.owner_id <> target_owner_id then
      raise exception 'Purchase transaction belongs to another owner';
    end if;

    if receipt_row.product_id <> target_product_id then
      raise exception 'Purchase transaction product mismatch';
    end if;

    if receipt_row.status = 'verified' then
      select coin_balance
      into next_balance
      from public.profiles
      where id = target_owner_id;

      return jsonb_build_object(
        'already_processed', true,
        'coin_amount', pack_row.coin_amount,
        'coin_balance', next_balance,
        'receipt_id', receipt_row.id
      );
    end if;

    update public.purchase_receipts
    set
      status = 'verified',
      purchased_amount = pack_row.coin_amount,
      price_cents = pack_row.price_cents,
      currency = pack_row.currency,
      raw_receipt_hash = target_raw_receipt_hash,
      context = coalesce(context, '{}'::jsonb) || coalesce(verification_context, '{}'::jsonb),
      verified_at = timezone('utc', now())
    where id = receipt_row.id
    returning *
    into receipt_row;
  else
    insert into public.purchase_receipts (
      owner_id,
      platform,
      product_id,
      transaction_id,
      status,
      purchased_amount,
      price_cents,
      currency,
      raw_receipt_hash,
      context,
      verified_at
    )
    values (
      target_owner_id,
      target_platform,
      target_product_id,
      target_transaction_id,
      'verified',
      pack_row.coin_amount,
      pack_row.price_cents,
      pack_row.currency,
      target_raw_receipt_hash,
      coalesce(verification_context, '{}'::jsonb),
      timezone('utc', now())
    )
    returning *
    into receipt_row;
  end if;

  update public.profiles
  set
    coin_balance = coin_balance + pack_row.coin_amount,
    updated_at = timezone('utc', now())
  where id = target_owner_id
  returning coin_balance
  into next_balance;

  return jsonb_build_object(
    'already_processed', false,
    'coin_amount', pack_row.coin_amount,
    'coin_balance', next_balance,
    'receipt_id', receipt_row.id
  );
end;
$$;

revoke all on function public.grant_verified_coin_purchase(
  uuid,
  text,
  text,
  text,
  text,
  jsonb
) from public, anon, authenticated;

grant execute on function public.grant_verified_coin_purchase(
  uuid,
  text,
  text,
  text,
  text,
  jsonb
) to service_role;
