-- Base auth and horse domain schema.
-- Apply first.

create extension if not exists pgcrypto;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  profile_display_name text;
  base_handle text;
  profile_handle text;
  profile_email text;
begin
  profile_email := coalesce(new.email, new.id::text || '@pivot.local');
  profile_display_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
    split_part(profile_email, '@', 1),
    'Player'
  );
  base_handle := '@' || lower(
    regexp_replace(profile_display_name, '[^a-zA-Z0-9]+', '', 'g')
  );
  if base_handle = '@' then
    base_handle := '@player';
  end if;
  profile_handle := base_handle;

  if exists (select 1 from public.profiles where handle = profile_handle) then
    profile_handle := base_handle || substr(replace(new.id::text, '-', ''), 1, 8);
  end if;

  insert into public.profiles (
    id,
    email,
    display_name,
    handle,
    stable_name,
    favorite_breed,
    accent_value,
    coin_balance
  )
  values (
    new.id,
    profile_email,
    profile_display_name,
    profile_handle,
    profile_display_name || ' Stable',
    'Arabian',
    15003876,
    7000
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  display_name text not null,
  handle text unique not null,
  stable_name text not null,
  bio text not null default '',
  favorite_breed text not null default 'Arabian',
  accent_value integer not null default 15003876,
  coin_balance integer not null default 7000,
  inventory jsonb not null default '{}'::jsonb,
  stable_expansion_tier integer not null default 0,
  stable_expansion_renews_at text,
  prenatal_boosted_pregnancy_ids jsonb not null default '[]'::jsonb,
  carrot_boosted_horse_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.horses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  registry_id text unique not null,
  registered_name text not null,
  current_name text not null,
  breed text not null,
  sex text not null,
  generation integer not null default 1,
  age_days integer not null default 1,
  breeding_retirement_days integer not null default 35,
  starter_tier text not null,
  price integer not null default 0,
  transfer_count integer not null default 0,
  is_mutant boolean not null default false,
  is_public_listing boolean not null default false,
  is_featured_profile_horse boolean not null default false,
  is_listed_for_sale boolean not null default false,
  genetic_profile jsonb not null default '{}'::jsonb,
  care_stats jsonb not null default '{}'::jsonb,
  lineage_memory jsonb not null default '{}'::jsonb,
  special_traits jsonb not null default '[]'::jsonb,
  dam_snapshot jsonb,
  sire_snapshot jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.horse_traits (
  id bigint generated by default as identity primary key,
  horse_id uuid not null references public.horses(id) on delete cascade,
  trait_type text not null,
  trait_option text not null,
  rarity text not null,
  sort_order integer not null default 0
);

alter table public.profiles enable row level security;
alter table public.horses enable row level security;
alter table public.horse_traits enable row level security;

drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read"
on public.profiles
for select
using (true);

drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update"
on public.profiles
for update
using (auth.uid() = id);

drop policy if exists "profiles owner insert" on public.profiles;
create policy "profiles owner insert"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "horses public read" on public.horses;
create policy "horses public read"
on public.horses
for select
using (
  is_public_listing = true
  or is_featured_profile_horse = true
  or is_listed_for_sale = true
  or auth.uid() = owner_id
);

drop policy if exists "horses owner write" on public.horses;
create policy "horses owner write"
on public.horses
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "horse traits readable with horse visibility" on public.horse_traits;
create policy "horse traits readable with horse visibility"
on public.horse_traits
for select
using (
  exists (
    select 1
    from public.horses
    where horses.id = horse_traits.horse_id
      and (
        horses.is_public_listing = true
        or horses.is_featured_profile_horse = true
        or horses.is_listed_for_sale = true
        or horses.owner_id = auth.uid()
      )
  )
);

drop policy if exists "horse traits owner write" on public.horse_traits;
create policy "horse traits owner write"
on public.horse_traits
for all
using (
  exists (
    select 1
    from public.horses
    where horses.id = horse_traits.horse_id
      and horses.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.horses
    where horses.id = horse_traits.horse_id
      and horses.owner_id = auth.uid()
  )
);

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
